# docs: https://changie.dev/config/
---
changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: "### {{.Kind}}"
changeFormat: "* [#{{.Custom.Issue}}](https://github.com/{{.Env.GITHUB_REPOSITORY}}/issues/{{.Custom.Issue}}) {{.Body}}"
kinds:
  - label: 💥 Breaking
    key: breaking
    auto: minor
  - label: ✨ Added
    key: added
    auto: minor
  - label: 💫 Changed
    key: changed
    auto: minor
  - label: ⚰️ Deprecated
    key: deprecated
    auto: minor
  - label: 🗑️ Removed
    key: removed
    auto: minor
  - label: 🪲 Fixed
    key: fixed
    auto: patch
  - label: 🚨 Security
    key: security
    auto: patch
  - label: 📚 Documentation
    key: documentation
    auto: patch
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
  afterKind: 1
  beforeKind: 1
envPrefix: CHANGIE_
custom:
  - key: Issue
    label: Issue/PR Number
    type: int
    minInt: 1
replacements:
  - path: ./examples/provider/provider.tf
    find: ' version = ".*"'
    replace: ' version = "{{.VersionNoPrefix}}"'
  - path: ./templates/guides/getting_started.md.tmpl
    find: '          version = ".*"'
    replace: '          version = "{{.VersionNoPrefix}}"'
