# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: 🖇️ Assign author to PR

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            if (context.payload.pull_request.user.type === "Bot") {
                return;
            }

            github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.payload.pull_request.user.login],
            });
